### ISSUE TITLE
Fix Google mobile warnings

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-site#211]
Fix the mobile warnings identified by Google.

https://search.google.com/search-console/core-web-vitals/summary?resource_id=sc-domain%3Agrommet.io&device=2

**Comment by ericsoderberghp** [comment]
![Screen Shot 2021-04-01 at 8 32 00 AM](https://user-images.githubusercontent.com/11637956/113317905-bbfb8380-92c4-11eb-9e2b-dd037ad2c2bd.png)

**Comment by ShimiSun** [comment]
I'm getting this message as I try to open the link
![image](https://user-images.githubusercontent.com/6320236/113319364-94111d80-92ce-11eb-95f4-85ac7964a3ea.png)

**Comment by taysea** [comment]
It seems that one thing strongly affecting the analytics score is the animations which causes the entire page to repaint every time the animation switches. See video below. I have enabled "paint flashing" which flashes green on what parts of the window are being repainted.

https://user-images.githubusercontent.com/12522275/114616574-e140a800-9c5b-11eb-82c8-225d826183fb.mov


Before and after lighthouse score where all I did was comment out the animation on the top of the page and the animations slightly on the page:

BEFORE
<img width="582" alt="Screen Shot 2021-04-13 at 1 39 54 PM" src="https://user-images.githubusercontent.com/12522275/114618044-c0795200-9c5d-11eb-874f-8a2d6ed06b94.png">

AFTER (without animated sections)
<img width="586" alt="Screen Shot 2021-04-13 at 1 32 18 PM" src="https://user-images.githubusercontent.com/12522275/114618071-ca9b5080-9c5d-11eb-828f-a3f058181d65.png">


Items to note: Improvement of LCP (Largest Content Paint) and Speed Index and remove of any CLS (Layout Shift).

Items to ignore: The time to interactive is much more elevated than the deployed site. I believe this is because the locally server does not use HTTP2 which Lighthouse is wanting (the deployed site uses HTTP2).

However, the Time to Interactive still could be improved but playing around with lazy-loading images/dynamically importing the components on the homepage had no affect on this value. Open to thoughts from others around what to try.

**Comment by ericsoderberghp** [comment]
Would it help to make the hero animation stuff a separate component? Although, I thought it already was one.

**Comment by taysea** [comment]
It is already its own component. Seems like we'd need to adjust how the CSS is being built up for the animations, however most of those are coming from internal Grommet animations, so I don't know that we have direct access to the underlying boxes. This link talks about using the additional CSS prop of `will-change: transform` to indicate areas that will change. However, there are performance downsides when you use this too much and I wonder if given the number of animated regions we have if that will be a negative instead of positive. Would have to read more.

My larger interest I think is how to bring down the Time To Interactive score which corresponds to "FID". All the things I tried (lazy load images, dynamically import components) wasn't doing anything to improve the FID score. Wondering what other things should be tried?

**Comment by ericsoderberghp** [comment]
When I can't think of anything concrete, I switch to some form of binary search, like removing all content from the home screen and seeing what the score is. If it's still bad, it has nothing to do with the content, and perhaps we should explore how we are packaging things. If the score improves, slowly add content back until we find what offends. Just a thought.
