### ISSUE TITLE
Upgrade grommet-site dependencies

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-site#306]
- [] `yarn upgrade --latest`
- [] upgrade corresponding code for breaking changes
- [] Ensure https://github.com/grommet/grommet-site/security/dependabot is clear

**Comment by MikeKingdom** [comment]
offline-plugin isn't working with webpack 5 and offline-plugin dev has been stale for at least 2 years.

The issue is basically [this](https://github.com/NekR/offline-plugin/issues/491)

So should we replace offline-plugin with something being maintained and newer like https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin?
Migration info seems to be [here](https://webpack.js.org/guides/progressive-web-application/)

Or another option might be to use a [fork that fixes offline-plugin](https://www.npmjs.com/package/@lcdp/offline-plugin) but it seems like migrating to workbox-webpack-plugin might be a better path forward.

**Comment by ericsoderberghp** [comment]
I lean towards moving towards the future.
